FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm ci --force --loglevel verbose
COPY . .
ARG BASE_API_URL
ARG BASE_WEB_URL
RUN echo "BASE_API_URL=$BASE_API_URL" > .env \
 && echo "BASE_WEB_URL=$BASE_WEB_URL" >> .env
RUN npm run build
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 